package com.woniuxy.pojo;

public class Jianda {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.title
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.answer
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.typeid
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.test_question_id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private Integer testQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.type
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.id
     *
     * @return the value of jianda.id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.id
     *
     * @param id the value for jianda.id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.title
     *
     * @return the value of jianda.title
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.title
     *
     * @param title the value for jianda.title
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.answer
     *
     * @return the value of jianda.answer
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.answer
     *
     * @param answer the value for jianda.answer
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.typeid
     *
     * @return the value of jianda.typeid
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.typeid
     *
     * @param typeid the value for jianda.typeid
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.test_question_id
     *
     * @return the value of jianda.test_question_id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.test_question_id
     *
     * @param testQuestionId the value for jianda.test_question_id
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.type
     *
     * @return the value of jianda.type
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.type
     *
     * @param type the value for jianda.type
     *
     * @mbg.generated Tue Aug 27 17:20:31 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }
}