package com.woniuxy.pojo;

public class MultipleChoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.option1
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String option1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.option2
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String option2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.option3
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String option3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.option4
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String option4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiple_choice.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer testQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.id
     *
     * @return the value of multiple_choice.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.id
     *
     * @param id the value for multiple_choice.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.title
     *
     * @return the value of multiple_choice.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.title
     *
     * @param title the value for multiple_choice.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.option1
     *
     * @return the value of multiple_choice.option1
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getOption1() {
        return option1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.option1
     *
     * @param option1 the value for multiple_choice.option1
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setOption1(String option1) {
        this.option1 = option1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.option2
     *
     * @return the value of multiple_choice.option2
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getOption2() {
        return option2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.option2
     *
     * @param option2 the value for multiple_choice.option2
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setOption2(String option2) {
        this.option2 = option2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.option3
     *
     * @return the value of multiple_choice.option3
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getOption3() {
        return option3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.option3
     *
     * @param option3 the value for multiple_choice.option3
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setOption3(String option3) {
        this.option3 = option3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.option4
     *
     * @return the value of multiple_choice.option4
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getOption4() {
        return option4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.option4
     *
     * @param option4 the value for multiple_choice.option4
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setOption4(String option4) {
        this.option4 = option4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.answer
     *
     * @return the value of multiple_choice.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.answer
     *
     * @param answer the value for multiple_choice.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.typeid
     *
     * @return the value of multiple_choice.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.typeid
     *
     * @param typeid the value for multiple_choice.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiple_choice.test_question_id
     *
     * @return the value of multiple_choice.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiple_choice.test_question_id
     *
     * @param testQuestionId the value for multiple_choice.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }
}