package com.woniuxy.pojo;

public class QuestionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_type.typename
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.typeid
     *
     * @return the value of question_type.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.typeid
     *
     * @param typeid the value for question_type.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.typename
     *
     * @return the value of question_type.typename
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.typename
     *
     * @param typename the value for question_type.typename
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }
}