package com.woniuxy.pojo;

public class Tiankong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    private Integer testQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.id
     *
     * @return the value of tiankong.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.id
     *
     * @param id the value for tiankong.id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.title
     *
     * @return the value of tiankong.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.title
     *
     * @param title the value for tiankong.title
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.answer
     *
     * @return the value of tiankong.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.answer
     *
     * @param answer the value for tiankong.answer
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.typeid
     *
     * @return the value of tiankong.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.typeid
     *
     * @param typeid the value for tiankong.typeid
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.test_question_id
     *
     * @return the value of tiankong.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.test_question_id
     *
     * @param testQuestionId the value for tiankong.test_question_id
     *
     * @mbg.generated Tue Aug 27 16:03:12 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }
}