package com.woniuxy.mapper;

import java.util.List;

import com.woniuxy.pojo.Jianda;
import com.woniuxy.pojo.JiandaExample;
import org.apache.ibatis.annotations.Param;

public interface JiandaMapper {
	List<Jianda> findAll();
    List<Jianda> findByPage(Integer page,Integer limit);

    List<Jianda> findAllByType(String typename);
    List<Jianda> findByType(String typename,Integer page,Integer limit);

    List<Jianda> findAllByQType(String typename);
    List<Jianda> findByQType(String typename,Integer page,Integer limit);
    
    List<Jianda> findAllByName(String name);
    List<Jianda> findByName(String name,Integer page,Integer limit);
    
    List<Jianda> findAllByTwo(String typename,String typename2);
    List<Jianda> findByTwo(String typename,String typename2,Integer page, Integer limit);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    long countByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByPrimaryKey(Integer jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insert(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insertSelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    List<Jianda> selectByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    Jianda selectByPrimaryKey(Integer jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExample(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKeySelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKey(Jianda record);
}