package com.woniuxy.mapper;

import java.util.List;

import com.woniuxy.pojo.TestQuestions;
import com.woniuxy.pojo.TestQuestionsExample;
import org.apache.ibatis.annotations.Param;

public interface TestQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    long countByExample(TestQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByExample(TestQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByPrimaryKey(Integer testQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insert(TestQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insertSelective(TestQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    List<TestQuestions> selectByExample(TestQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    TestQuestions selectByPrimaryKey(Integer testQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestQuestions record, @Param("example") TestQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExample(@Param("record") TestQuestions record, @Param("example") TestQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKeySelective(TestQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_questions
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKey(TestQuestions record);
}