package com.woniuxy.mapper;

import java.util.List;

import com.woniuxy.pojo.Trueorfalse;
import com.woniuxy.pojo.TrueorfalseExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TrueorfalseMapper {

	List<Trueorfalse> findAll();
    List<Trueorfalse> findByPage(Integer page,Integer limit);
    
    List<Trueorfalse> findAllByType(String typename);
    List<Trueorfalse> findByType(String typename,Integer page,Integer limit);
    
    List<Trueorfalse> findAllByQType(String typename);
    List<Trueorfalse> findByQType(String typename,Integer page,Integer limit);

    List<Trueorfalse> findAllByName(String name);
    List<Trueorfalse> findByName(String name, Integer page,Integer limit);
    
    List<Trueorfalse> findAllByTwo(String typename,String typename2);
    List<Trueorfalse> findByTwo(String typename,String typename2,Integer page, Integer limit);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    long countByExample(TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByExample(TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByPrimaryKey(Integer tfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insert(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insertSelective(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    List<Trueorfalse> selectByExample(RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    Trueorfalse selectByPrimaryKey(Integer tfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trueorfalse record, @Param("example") TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExample(@Param("record") Trueorfalse record, @Param("example") TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKeySelective(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKey(Trueorfalse record);

}